### ISSUE TITLE
Traceback: RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 1000.

### ISSUE THREAD

**Issue by estods3** [estods3/Sampling-usingNyquistTheorem#1]
Traceback (most recent call last):
  File "runSimulation.py", line 26, in <module>
    env.redrawEnv(inputSig, samplingFreqSelection, t)
  File "/home/estods/Documents/projects/Sampling-usingNyquistTheorem/src/environment.py", line 89, in redrawEnv
    res = fit_sin(a, b, timeToSamplesConversion)
  File "/home/estods/Documents/projects/Sampling-usingNyquistTheorem/src/environment.py", line 83, in fit_sin
    popt, pcov = scipy.optimize.curve_fit(sinfunc, tt, yy, p0=guess)
  File "/usr/local/lib/python2.7/dist-packages/scipy/optimize/minpack.py", line 748, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 1000.

**Comment by estods3** [comment]
error is triggered when the sampling freq is dragged to a value too low for the function to work. implement a stop at a threshold.
